In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [2]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
#performance LR
lr = LogisticRegression(max_iter=3000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

/Users/bijayamanandhar/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [4]:
#performance SVC
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [5]:
#performance RForest
rf = RandomForestClassifier(n_estimators=30)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9574074074074074

In [6]:
#k-fold
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
#splits train data and test data into 2:1 ratio out of total 3 folds, split is 3
#test_size is 0.3 here
for train_index, test_index in kf.split([_ for _ in range(1,10)]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
#for simplicity, we define a generic method
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [9]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

/Users/bijayamanandhar/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [10]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9833333333333333

In [11]:
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits=3)

In [12]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],\
    digits.target[train_index],digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(max_iter=3000),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=30),X_train,X_test,y_train,y_test))
    
print(f'{scores_lr = }\n{scores_svm = }\n{scores_rf = }')

/Users/bijayamanandhar/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


scores_lr = [0.9282136894824707, 0.9415692821368948, 0.9165275459098498]
scores_svm = [0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
scores_rf = [0.9215358931552587, 0.9565943238731218, 0.9148580968280468]


In [13]:
# In real life, we can avoiding above code. 
#It can be done using `from sklearn.model_selection`
#'import cross_val_score'
from sklearn.model_selection import cross_val_score

In [14]:
cross_val_score(LogisticRegression(max_iter=4000), digits.data,digits.target)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [15]:
cross_val_score(SVC(), digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [16]:
cross_val_score(RandomForestClassifier(n_estimators=30), digits.data,digits.target)

array([0.91388889, 0.91388889, 0.94986072, 0.96657382, 0.92200557])

In [17]:
#Exercise: do the above in iris flower data

In [18]:
import numpy as np
np.__version__

'1.22.0'

In [19]:
np.__version__

'1.22.0'